//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Haminhtrung_0279.Context
{
    public partial class OrderDetail
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
