//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Haminhtrung_0279.Context
{
    public partial class Order
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
    }
}
