//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Haminhtrung_0279.Context
{
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
    }
}
